Scheduling regular updates in the interest of creating https://dev.opera.com/articles/better-performance-with-requestanimationframe[smooth running] browser animations in JS might +
conceivably look a bit like,

[source,js]
----
// Start
window.requestAnimationFrame(loop)

function loop(now) {
  console.log(`update called ${now}ms into current document's lifetime`)

  // Repeat endlessly?
  window.requestAnimationFrame(loop)
}
----

Ending that loop on demand such as when https://www.html5rocks.com/en/tutorials/speed/animations/#debouncing-mouse-events[debouncing mouse events] would involve keeping track of each `requestAnimationFrame` or *rAF* index to then be calling https://developer.mozilla.org/en-US/docs/Web/API/Window/cancelAnimationFrame[`cancelAnimationFrame`] with,

[source,js]
----
// Start
let frameIndex = window.requestAnimationFrame(loop)

function loop() {
  // Update
  frameIndex = window.requestAnimationFrame(loop)
}

function stop() {
  if (frameIndex) {
    // Unassign, make falsy again
    frameIndex = window.cancelAnimationFrame(frameIndex)
  }

  console.assert(frameIndex === undefined)
}

document.addEventListener('click', stop, { once: true })
----

This module is essentially a closure around that otherwise free roaming frame reference. It includes no polyfill and minifies to less than half a kilobyte.

[source,sh]
----
# Includes ES and CJS versions
npm i @thewhodidthis/animation
----

The default and only export is an anonymous function requiring a callback argument to be invoked before the next repaint, same as using rAF directly. In line with the https://addyosmani.com/resources/essentialjsdesignpatterns/book/#revealingmodulepatternjavascript[revealing module pattern] expect an anonymous object with `start()`  and `stop()` methods attached and aliased link:/index.mjs#L39[play / pause] respectively.

[source,js]
----
import createLoop from '@thewhodidthis/animation'

let frameIndexMaybe

const animation = createLoop((now, frameIndex) => {
  console.assert(frameIndexMaybe === frameIndex)

  frameIndexMaybe = animation.stop()

  console.assert(frameIndexMaybe === undefined)
})

console.assert(Object.keys(animation).every(k => ['start', 'stop', 'play', 'pause'].includes(k)))

frameIndexMaybe = animation.start()
----

The callback is passed a https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp[`DOMHighResTimeStamp`] and the frame reference. Just in case, checks are included to allow for running multiple loops in parallel.
